name: Geometry-Build
on: [push]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Buildozer-Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload-Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Geometry-AI-APK
          path: bin/*.apk
