name: Geometry-Build
on: [push]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Geometry-AI-APK
          path: bin/*.apk
