name: Geometry-AI-Offline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Guardar APK
        uses: actions/upload-artifact@v3
        with:
          name: Geometry-AI-APK
          path: bin/*.apk
          
